### ISSUE TITLE
Internal Server Error on "Verwaltung"

### ISSUE THREAD

**Issue by johannes-bittner** [heimrichhannot/contao-pwa-bundle#11]
After the creation of a PWA configuration (fresh Contao 4.9.5 installation), when clicking on "Verwaltung", the server responds with an Internal Server Error and the following error message: 

`Block "error" on template "@ContaoCore/Backend/be_page.html.twig" does not exist.`

minishlink/web-push is installed.

**Comment by koertho** [comment]
@johannes-bittner Thanks for reporting. Should be fixed in 0.7.4.
