### ISSUE TITLE
Php error on sending messages

### ISSUE THREAD

**Issue by sfx12** [heimrichhannot/contao-pwa-bundle#12]
I get 2 errors when sending messages.. one when write and send one.. and the other when click on "send unsended messages" in the Backend:

`Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\UndefinedMethodError: "Attempted to call an undefined method named "sendNotification" of class "Minishlink\WebPush\WebPush". Did you mean to call e.g. "queueNotification" or "sendOneNotification"?" at /var/customers/webs/id0/mobilworld/vendor/heimrichhannot/contao-pwa-bundle/src/Sender/PushNotificationSender.php line 131 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\UndefinedMethodError(code: 0): Attempted to call an undefined method named \"sendNotification\" of class \"Minishlink\\WebPush\\WebPush\".\nDid you mean to call e.g. \"queueNotification\" or \"sendOneNotification\"? at /var/customers/webs/id0/mobilworld/vendor/heimrichhannot/contao-pwa-bundle/src/Sender/PushNotificationSender.php:131)"} `

and the other error is:

`request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: "No route found for "GET /contao/pwa/pushnotification/send": Method Not Allowed (Allow: POST)" at /var/customers/webs/id0/myfolder/vendor/symfony/http-kernel/EventListener/RouterListener.php line 140 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"GET /contao/pwa/pushnotification/send\": Method Not Allowed (Allow: POST) at /var/customers/webs/id0/mobilworld/vendor/symfony/http-kernel/EventListener/RouterListener.php:140, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /var/customers/webs/id0/mobilworld/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:42)"} []`

i have Contao 4.93

**Comment by koertho** [comment]
Hi, the error sound like you have the wrong web push library installed. Be sure to have version 5.x installed, not 6 or something before!

**Comment by koertho** [comment]
Closing due inactivity
