### ISSUE TITLE
Push Notification Abonnieren Button shows "Es wird geprüft, ob Ihr Browser Push-Benachrichtigungen unterstützt"

### ISSUE THREAD

**Issue by srothe** [heimrichhannot/contao-pwa-bundle#15]
Hi,
thank you for your extension!

After i think a correct (of course i think so ;-) ) installation of contao-pwa-bundle and contao-head-bundle, implementing the First Steps and adding the Push Notification Abonnieren Button to the Frontend, the Button only shows "Es wird geprüft, ob Ihr Browser Push-Benachrichtigungen unterstützt"

I also can't follow the steps using the control link in backend (see https://github.com/heimrichhannot/contao-pwa-bundle/issues/14), maybe this is a follow up.

Best
sven

**Comment by koertho** [comment]
Hi, please always provide contao-, php- and bundle version. I just fixed a exception lead to such an issue. Maybe it is fixed for you.
