### ISSUE TITLE
error: type Array

### ISSUE THREAD

**Issue by lizardat** [heimrichhannot/contao-pwa-bundle#19]
**Context**
Contao version: 4.13.28
Bundle version: 0.8.15
PHP version: 8.1.18

**Description**
When trying to delete a sent notification in the list (or all of them) I get this error message:
`Internal Server Error
Was ist das Problem?
in_array(): Argument #2 ($haystack) must be of type array, string given`

**Comment by koertho** [comment]
@lizardat Thanks for reporting. Shound be fixed in 0.8.16
