### ISSUE TITLE
Can't access push notifications or subscribers

### ISSUE THREAD

**Issue by mktcode** [heimrichhannot/contao-pwa-bundle#2]
I managed to get everything to work by following the instructions in the readme but when I try to access Push Notifications or Subscribers from the PWA Configuration page, I get the following errors:

`Table "tl_pwa_pushnotifications" is not allowed in module "huh_pwa_configurations".`
`Table "tl_pwa_pushsubscriber" is not allowed in module "huh_pwa_configurations".`

**Comment by mktcode** [comment]
Ok I found the issue... I'm not so familiar with contao but why aren't these tables configured as part of the module?

https://github.com/heimrichhannot/contao-pwa-bundle/blob/master/src/Resources/contao/config/config.php#L8

As far as I can see, everything works fine, once you add those tables to the configuration.

**Comment by koertho** [comment]
Thank you for reporting and fixing. This error didn't appear in our configuration. Can you provide your contao version?

**Comment by mktcode** [comment]
No problem! Thanks for being an active open source project!
