### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by valentin-** [heimrichhannot/contao-pwa-bundle#5]
Hi, after trying to install this extension I get following output.
All requirements and PHP dependencies are met.

Contao 4.8.4
PHP 7.2.19

Here is a list of your installed extensions.

![image](https://user-images.githubusercontent.com/90033/68049290-d0f47180-fce2-11e9-92e5-bd467e48c756.png)

![image](https://user-images.githubusercontent.com/90033/68049331-e7023200-fce2-11e9-81df-fc9af8be2672.png)

Do you have any suggestions?

**Comment by valentin-** [comment]
I've added some aliases in my project config.
```
services:
  HeimrichHannot\UtilsBundle\String\StringUtil: '@huh.utils.string'
  HeimrichHannot\HeadBundle\Manager\TagManager: '@huh.head.tag_manager'
  HeimrichHannot\ContaoPwaBundle\EventListener\CronjobListener: '@huh.pwa.listener.commandscheduler'
```

And I set the service `huh.pwa.listener.commandscheduler` to `public: true`

Now it's working fine.

**Comment by koertho** [comment]
Hi, I'll try to catch all service definitions ;)

**Comment by koertho** [comment]
@valentin- I just updated pwa, utils and head bundle, would love to hear if  it works now.

**Comment by valentin-** [comment]
@koertho sorry for the late response. I've tried it about two weeks ago without but the error still occured. Somehow it's working now, probably because i switched to PHP 7.4 (from 7.2).
