### ISSUE TITLE
Installation through Contao Manager not possible

### ISSUE THREAD

**Issue by valentin-** [heimrichhannot/contao-pwa-bundle#6]
Installing Contao PWA Bundle using CM is not possible:

```
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception 
In ScriptHandler.php line 88: An error occurred while executing the "contao:install-web-dir" command: 
```

Command line `composer require` works fine, but installation through CM using the generated package.lock file still fails.

**Comment by koertho** [comment]
Hi, sorry for the late responce. We need more information (a more detailed error log), since the given error log says nothing. Also please provide Contao and PHP version.

**Comment by valentin-** [comment]
Hi, thanks for your response. Unfortunately I can't figure it out and there isn't a detailed error log.

I've set up a fresh Contao 4.8.5 (PHP 7.2.19) installation using minimal setup mode in CM.

Installation using command line works fine:
* heimrichhannot/contao-doctrine-cache-fix
* heimrichhannot/contao-encore-bundle
* heimrichhannot/contao-pwa-bundle

When trying to run the `composer install` command through CM (using the generate composer.lock file), it won't work and the setup is completely broken. After running `composer install` using the command line the installation is fixed again.

composer.json and composer.lock attached [composer.zip](https://github.com/heimrichhannot/contao-pwa-bundle/files/3860205/composer.zip)

![image](https://user-images.githubusercontent.com/90033/69081043-70cd3180-0a3d-11ea-965c-c97fadbdaa16.png)

**Comment by koertho** [comment]
From the error log it looks like the error is thrown, when symlinks are created, not on bundle install. Also the riak cache error shows up (which shouldn't with doctrine/cache: ^1.9). Please try without the doctrine cache fix bundle.

**Comment by valentin-** [comment]
As mentioned in the other issue, the installation is working now. 

When opening `/contao/pwa/control` I get following error (Contao error message) - but I don't think that's extension related. Once removing the error variable it's working.
`Block "error" on template "@ContaoCore/Backend/be_page.html.twig" does not exist.`

Also when activating debug mode some routes can't be found:

- /contao?do=huh_pwa_configurations&ref=8i_6wcxw -> `None of the chained routers were able to generate route: Route 'huh_pwa_backend_control' not found`
- /contao?do=huh_pwa_configurations&ref=6oI-tDmS -> `None of the chained routers were able to generate route: Route 'huh_pwa_backend_control' not found`
- /de/ (Frontend) -> `Unable to generate a URL for the named route "push_notification_subscription" as such route does not exist.`

But the extension itself seems to be working fine!

**Comment by koertho** [comment]
@valentin- Since this is non-related issue, please open up a new one.
