### ISSUE TITLE
DCA tl_page rootfallback palette

### ISSUE THREAD

**Issue by jelomada** [heimrichhannot/contao-pwa-bundle#8]
Hi!
In https://github.com/heimrichhannot/contao-pwa-bundle/blob/master/src/Resources/contao/dca/tl_page.php file fields are added to `root` palette, these fields should be also added to `rootfallback` palette.

`$dca['palettes']['root']           = str_replace('{publish_legend', '{pwa_legend},addPwa;{publish_legend', $dca['palettes']['root']);`
you should add it also to rootfallback palette:
`$dca['palettes']['rootfallback']           = str_replace('{publish_legend', '{pwa_legend},addPwa;{publish_legend', $dca['palettes']['rootfallback']);`

**Comment by koertho** [comment]
@jelomada Should be fixed in 0.7.1.
